"""Explicit morphological groups; source answers are never rewritten."""

import re

STOP = set(
    "E È DI A AD AL ALL ALLA ALLE ALLO AI AGLI ANCHE CHE CI CON DA DEI DEL DELLA "
    "DI ERO FA GLI HO I IL IN LA LE LO MA MI MOLTO NE NN NON PER PERÒ PIÙ PO "
    "POCO QUALCOSA SE SI SIA SONO STATA STATO TANTISSIMO TROPPO TUTTO UN UNA UNO".split()
)
GROUPS = {
    "NUOVO/A": "NUOVO NUOVA NUOVI NUOVE",
    "DIFFICILE": "DIFFICILE DIFFICILI",
    "DIVERTITO/A": "DIVERTITO DIVERTITA DIVERTITI DIVERTITE",
    "OTTIMO/A": "OTTIMO OTTIMA OTTIMI OTTIME",
    "BUONO/A": "BUONO BUONA BUONI BUONE",
    "PIACIUTO/A": "PIACIUTO PIACIUTA PIACIUTI PIACIUTE",
    "IMMERSIVO/A": "IMMERSIVO IMMERSIVA IMMERSIVI IMMERSIVE",
    "INCLUSIVO/A": "INCLUSIVO INCLUSIVA INCLUSIVI INCLUSIVE",
    "INFORMATIVO/A": "INFORMATIVO INFORMATIVA INFORMATIVI INFORMATIVE",
    "STIMOLANTE": "STIMOLANTE STIMOLANTI",
    "APPASSIONANTE": "APPASSIONANTE APPASSIONANTI",
    "ACCATTIVANTE": "ACCATTIVANTE ACCATTIVANTI",
    "AVVINCENTE": "AVVINCENTE AVVINCENTI",
    "UTILE": "UTILE UTILI",
    "PIACEVOLE": "PIACEVOLE PIACEVOLI",
    "BELLO/BELLA": "BELLO BELLA BELLI BELLE",
    "BELLISSIMO/A": "BELLISSIMO BELLISSIMA BELLISSIMI BELLISSIME BELISSIMO BELISSIMA",
    "CARINO/A": "CARINO CARINA CARINI CARINE",
    "BUFFO/A": "BUFFO BUFFA BUFFI BUFFE",
    "ISTRUTTIVO/A": "ISTRUTTIVO ISTRUTTIVA ISTRUTTIVI ISTRUTTIVE",
    "EDUCATIVO/A": "EDUCATIVO EDUCATIVA EDUCATIVI EDUCATIVE EDUCATTIVA",
    "FORMATIVO/A": "FORMATIVO FORMATIVA FORMATIVI FORMATIVE",
    "DIDATTICO/A": "DIDATTICO DIDATTICA DIDATTICI DIDATTICHE",
    "SIMPATICO/A": "SIMPATICO SIMPATICA SIMPATICI SIMPATICHE",
    "GIOCOSO/A": "GIOCOSO GIOCOSA GIOCOSI GIOCOSE",
    "UNICO/A": "UNICO UNICA UNICI UNICHE",
    "INTERATTIVO/A": "INTERATTIVO INTERATTIVA INTERATTIVI INTERATTIVE",
    "INNOVATIVO/A": "INNOVATIVO INNOVATIVA INNOVATIVI INNOVATIVE",
    "STUPENDO/A": "STUPENDO STUPENDA STUPENDI STUPENDE",
    "FANTASTICO/A": "FANTASTICO FANTASTICA FANTASTICI FANTASTICHE",
    "CURIOSO/A": "CURIOSO CURIOSA CURIOSI CURIOSE",
    "CREATIVO/A": "CREATIVO CREATIVA CREATIVI CREATIVE",
    "DINAMICO/A": "DINAMICO DINAMICA DINAMICI DINAMICHE",
    "DIVERSO/A": "DIVERSO DIVERSA DIVERSI DIVERSE",
    "COMPLESSO/A": "COMPLESSO COMPLESSA COMPLESSI COMPLESSE",
    "CORTO/A": "CORTO CORTA CORTI CORTE",
    "ALTERNATIVO/A": "ALTERNATIVO ALTERNATIVA ALTERNATIVI ALTERNATIVE",
    "ORIGINALE": "ORIGINALE ORIGINALI",
    "PARTICOLARE": "PARTICOLARE PARTICOLARI",
    "SENSAZIONALE": "SENSAZIONALE SENSAZIONALI",
    "INDIMENTICABILE": "INDIMENTICABILE INDIMENTICABILI",
    "INTRIGANTE": "INTRIGANTE INTRIGANTI",
    "INTELLIGENTE": "INTELLIGENTE INTELLIGENTI",
    "FACILE": "FACILE FACILI",
    "INFANTILE": "INFANTILE INFANTILI",
    "FICO/A": "FICO FICA FICHI FICHE",
    "GANZO/A": "GANZO GANZA GANZI GANZE",
    "NOIOSO/A": "NOIOSO NOIOSA NOIOSI NOIOSE",
    "SCIENTIFICO/A": "SCIENTIFICO SCIENTIFICA SCIENTIFICI SCIENTIFICHE",
    "ORGANIZZATO/A": "ORGANIZZATO ORGANIZZATA ORGANIZZATI ORGANIZZATE",
    "INTERESSANTE": "INTERESSANTE INTERESSANTI INTERESANTE INTERESANTI",
    "DIVERTENTE": "DIVERTENTE DIVERTENTI DIVERTENTISSIMA DIVERTENTISSIMO DIVERTENTISSIME DIVERTENTISSIMI DIVERTIMENTO",
    "COINVOLGENTE": "COINVOLGENTE COINVOLGENTI",
    "COINVOLGIMENTO": "COINVOLGIMENTO",
    "EMOZIONANTE": "EMOZIONANTE EMOZIONANTI",
    "ENTUSIASMANTE": "ENTUSIASMANTE ENTUSIASMANTI",
    "AFFASCINANTE": "AFFASCINANTE AFFASCINANTI",
    "COLLABORAZIONE": "COLLABORAZIONE",
    "CONCENTRAZIONE": "CONCENTRAZIONE",
    "CURIOSITÀ": "CURIOSITÀ CURIOSITA",
    "CULTURA": "CULTURA",
    "DELUSIONE": "DELUSIONE",
    "DIVULGAZIONE": "DIVULGAZIONE",
    "FELICITÀ": "FELICITÀ FELICITA",
    "IMPARARE": "IMPARARE",
    "NOVITÀ": "NOVITÀ NOVITA",
    "PUZZLE": "PUZZLE",
    "TOP": "TOP",
}
MAPPING = {word: label for label, words in GROUPS.items() for word in words.split()}
ALLOWED = set(GROUPS)


def exact_tokens(text):
    return {
        t
        for t in re.findall(r"[A-ZÀÈÉÌÒÙ]+", re.sub(r"\[[^]]*\]", "", text.upper()))
        if t not in STOP and len(t) > 1 and MAPPING.get(t, t) in ALLOWED
    }


def grouped_tokens(text):
    # Deduplicate AFTER grouping: BELLA BELLO in one answer counts once.
    return {MAPPING.get(t, t) for t in exact_tokens(text)}
