"""Explicit morphological groups; source answers are never rewritten."""

import re

STOP = set(
    "E È DI A DA IN CON PER CHE IL LO LA I GLI LE UN UNA UNO MOLTO STATA STATO ESPERIENZA ALLA HO MA NN NON PO TROPPO".split()
)
GROUPS = {
    "NUOVO/A": "NUOVO NUOVA NUOVI NUOVE",
    "DIFFICILE": "DIFFICILE DIFFICILI",
    "DIVERTITO/A": "DIVERTITO DIVERTITA DIVERTITI DIVERTITE",
    "OTTIMO/A": "OTTIMO OTTIMA OTTIMI OTTIME",
    "BUONO/A": "BUONO BUONA BUONI BUONE",
    "PIACIUTO/A": "PIACIUTO PIACIUTA PIACIUTI PIACIUTE",
    "IMMERSIVO/A": "IMMERSIVO IMMERSIVA IMMERSIVI IMMERSIVE",
    "INCLUSIVO/A": "INCLUSIVO INCLUSIVA INCLUSIVI INCLUSIVE",
    "INFORMATIVO/A": "INFORMATIVO INFORMATIVA INFORMATIVI INFORMATIVE",
    "STIMOLANTE": "STIMOLANTE STIMOLANTI",
    "UTILE": "UTILE UTILI",
    "PIACEVOLE": "PIACEVOLE PIACEVOLI",
    "BELLO/BELLA": "BELLO BELLA BELLI BELLE",
    "BELLISSIMO/A": "BELLISSIMO BELLISSIMA BELLISSIMI BELLISSIME",
    "CARINO/A": "CARINO CARINA CARINI CARINE",
    "ISTRUTTIVO/A": "ISTRUTTIVO ISTRUTTIVA ISTRUTTIVI ISTRUTTIVE",
    "EDUCATIVO/A": "EDUCATIVO EDUCATIVA EDUCATIVI EDUCATIVE EDUCATTIVA",
    "FORMATIVO/A": "FORMATIVO FORMATIVA FORMATIVI FORMATIVE",
    "SIMPATICO/A": "SIMPATICO SIMPATICA SIMPATICI SIMPATICHE",
    "GIOCOSO/A": "GIOCOSO GIOCOSA GIOCOSI GIOCOSE",
    "UNICO/A": "UNICO UNICA UNICI UNICHE",
    "INTERATTIVO/A": "INTERATTIVO INTERATTIVA INTERATTIVI INTERATTIVE",
    "INNOVATIVO/A": "INNOVATIVO INNOVATIVA INNOVATIVI INNOVATIVE",
    "STUPENDO/A": "STUPENDO STUPENDA STUPENDI STUPENDE",
    "FANTASTICO/A": "FANTASTICO FANTASTICA FANTASTICI FANTASTICHE",
    "CURIOSO/A": "CURIOSO CURIOSA CURIOSI CURIOSE",
    "NOIOSO/A": "NOIOSO NOIOSA NOIOSI NOIOSE",
    "SCIENTIFICO/A": "SCIENTIFICO SCIENTIFICA SCIENTIFICI SCIENTIFICHE",
    "ORGANIZZATO/A": "ORGANIZZATO ORGANIZZATA ORGANIZZATI ORGANIZZATE",
    "INTERESSANTE": "INTERESSANTE INTERESSANTI",
    "DIVERTENTE": "DIVERTENTE DIVERTENTI",
    "COINVOLGENTE": "COINVOLGENTE COINVOLGENTI",
    "EMOZIONANTE": "EMOZIONANTE EMOZIONANTI",
    "ENTUSIASMANTE": "ENTUSIASMANTE ENTUSIASMANTI",
    "AFFASCINANTE": "AFFASCINANTE AFFASCINANTI",
}
MAPPING = {word: label for label, words in GROUPS.items() for word in words.split()}


def exact_tokens(text):
    return {
        t
        for t in re.findall(r"[A-ZÀÈÉÌÒÙ]+", re.sub(r"\[[^]]*\]", "", text.upper()))
        if t not in STOP and len(t) > 1
    }


def grouped_tokens(text):
    # Deduplicate AFTER grouping: BELLA BELLO in one answer counts once.
    return {MAPPING.get(t, t) for t in exact_tokens(text)}
